sudo: false
os:
- linux
language: java
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
- chmod +x ./.utility/initiate_publish.sh
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
after_success:
- bash <(curl -s https://codecov.io/bash)
- "./.utility/initiate_publish.sh"
env:
  global:
  - secure: m9/UOaDUj/Zv2r8d/4JQCQzoRbIWPOA7PXCGq8bJIyOp6Ea7zPPnMG6GjjhcVpw4QMr66fIaaA8S1/dg9/CRdtwMbf6+eXPhhZ1/pKsuARuXd1c4u7+kiI7PERVj8CxW44OJ2LU1Jz3XEKiQ7aPCSGnv9hUbEtxaMjYHDG7ejQEUd3EgpkpHnHgvda9FsTJLCsqwca+S8XDh8trSdKOSEYfSQzQTPxaqYH0Q6+dKxc+zmtbdaFLXK9fuQLbjA/rRV33N3flmkcZzqE8lh915zM4i1nRPf2LwwsTqZjpa5xEql9B7G0Ka9twEckYcMPBQ+aC8ZXUu7iGnSfkhHgZpjc06WRIigqBcXHdt7ZAKectIKhmMhDwK5CNX/Ww0o2A1dOXI1+nWH1tu9/77VWxggt6yRlEcy3Q2xzlOGaEaJgcg4MYVDeZ/VpLvsiNMG7nBxK2lwLDgltflhzw2prbBtK6Jacga1b56ooQQGA5Q7KgZfvl8l0irZ5kJ9fl1al+zchixh2HFYa0QdBk0vAjeKSkOvYGvQDVUzdGBXHzsklo5y2R19Q1/iWWNjvm68thhf2NDNyz+ZtKSMPBEan5/sxjzDqzjKtxS49ve6QO5DKhgDFx1jdTIUqBScUi5cGqcVVph8g5fLzYp34XsOVy8IpNmVVrozlPEQjTBcdytdxU=
  - secure: lJTk6y05fULNQV1S92exj4n1Nl6l021nUO5S6W7+hHpODTQbqPaChzVqvSopx06+tzFHVUvxAvEx9fMnR0aqjgQx6mjYGKQFGEqU6l1J+hLKhHAptOfQ6uCNUdYswvCMtcTDwCDcnsWxbMzVloN5ooo3FpI3qYgXPMRa+8tMEmmkanzOL9xcht2D4R+Uu4m9Q3tBtgrAenVxMuqh4dubIHkONLRLJNiEP8eKj8Q7/VRlISC+2GzbVxST4lVAAnvixh5HcJGbK6b5HmQGMNry/hmJXfp+YK78rVgYEKvT4jgIVhtkPQuXaXPIHjtcN3IRSuV1MA5GMhqVm3vFXtzdKkQwvRriQjnMAES6IY07MuPV6xAmZH0/OWJFBhaC3LH0U8MADYOEtoBE8gcTnV1o+EbZSHIgA/wNUTs3KBfn4ttl/WqTxqdmWD8nFLqbaBNcYHW8akaUoaPhqY3KsqE0CIo6nTvE0X/ci13TyhgOwmwJpQU/n/nIJKb/B/deXiTaPHRw77+6MQsq40LqYdELc4PRrgHWml2HVbfVs30H+uhAxp1tNLFM3e4jguNgFo7CSb7VBSM+IaT7q6jfAeIw9YRiWQPJYLbTzzFtZifn4oJNM4okS1nl7votRmRZk2idJwqnQxC8hpNCoL3Wf5P/2OQy0NrunR58x2LRbH/Kx7k=
